[package]
name = "cypher-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"
libcypher-parser-sys = "0.6.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
